// Generated by scripts/generate-frontend-config.js.
// Do not edit this file manually.

export const FRONTEND_CONFIG = Object.freeze({
  "environment": "staging",
  "status": "active",
  "networkName": "BOT Chain Testnet",
  "chainId": 968,
  "chainIdHex": "0x3C8",
  "rpcUrl": "https://rpc.bohr.life",
  "explorerUrl": "https://scan.bohr.life",
  "faucetUrl": "https://faucet.botchain.ai/basic",
  "nativeCurrency": {
    "name": "BOT",
    "symbol": "BOT",
    "decimals": 18
  },
  "contractName": "BOTPass",
  "contractAddress": "0x2ea9E965433D8f42F9C0caa8BC223335f8e14f6C",
  "deploymentTransactionHash": "0x019995d38fd45d2e29f9b725255df823130be0768ec7ce0c87abb1c7cc1f5d10",
  "activationReviewed": true,
  "sourceVerified": false,
  "writesEnabled": true
});
