// Generated by scripts/generate-frontend-config.js.
// Do not edit this file manually.

export const FRONTEND_CONFIG = Object.freeze({
  "environment": "staging",
  "status": "pending",
  "networkName": "BOT Chain Testnet",
  "chainId": 968,
  "chainIdHex": "0x3C8",
  "rpcUrl": "https://rpc.bohr.life",
  "explorerUrl": "https://scan.bohr.life",
  "faucetUrl": "https://faucet.botchain.ai/basic",
  "nativeCurrency": {
    "name": "BOT",
    "symbol": "BOT",
    "decimals": 18
  },
  "contractName": "BOTPass",
  "contractAddress": null,
  "deploymentTransactionHash": null,
  "activationReviewed": false,
  "sourceVerified": false,
  "writesEnabled": false
});
