// Generated by scripts/generate-frontend-config.js.
// Do not edit this file manually.

export const FRONTEND_CONFIG = Object.freeze({
  "environment": "production",
  "status": "active",
  "networkName": "BOT Chain Mainnet",
  "chainId": 677,
  "chainIdHex": "0x2A5",
  "rpcUrl": "https://rpc.botchain.ai",
  "explorerUrl": "https://scan.botchain.ai",
  "faucetUrl": null,
  "nativeCurrency": {
    "name": "BOT",
    "symbol": "BOT",
    "decimals": 18
  },
  "contractName": "BOTPass",
  "contractAddress": "0x41fc0234A8f94482168B063FDE7ABE67043E68A4",
  "deploymentTransactionHash": "0xb86877c47c9b6b937f0142245d2c6e9083ed73e87d5b36b063d0624f43a7105f",
  "activationReviewed": true,
  "sourceVerified": true,
  "writesEnabled": true
});
